### ISSUE TITLE
Sync between two machines.

### ISSUE THREAD

**Issue by Stegosource** [hodgef/PRSS#4]
This is mostly a question, but does the project support being used across multiple machines? Or by multiple authors? Since it's using Git, I would imagine it is possible, but I also see that it's using SQLite, so Im not sure if that DB is being checked into the repo or not. I guess the real question is whether it supports Git pull as well as push?

It would be great if you could support multiple authors/machines.

**Comment by hodgef** [comment]
Hey @Stegosource,

Currently the site data is stored in two files

- prss.json (Contains the site ids, the repo name and username and app configs)
- prss.db (Contains the site posts, etc)

You can move prss.db to a different directory tracked by Git like so:

![image](https://user-images.githubusercontent.com/25509135/88315506-5f32dc80-cce4-11ea-8673-6bfc1670f0c6.png)
![image](https://user-images.githubusercontent.com/25509135/88323007-8ba02600-ccef-11ea-9159-31996497c0e6.png)


However when you install PRSS in your other computer you'd need to pull prss.db and send the prss.json file separately.. which is a bit inconvenient. There's no auto-pull or syncing mechanism as of yet.

Perhaps this could be improved. Feel free to suggest anything you'd like to see and I'll investigate. My goal is to improve the UX as much as possible.

Thanks,
Francisco Hodge
