### ISSUE TITLE
Did you use any UI framework?

### ISSUE THREAD

**Issue by SolomonLeon** [hodgef/PRSS#7]
The UI of this app looks so beautiful! 
Did you use any UI framework or did you develop it yourself?

**Comment by hodgef** [comment]
Hey @SolomonLeon ! 

It's built from scratch with React and bootstrap :) I'm working on an update for this app that I'm aiming to deliver soon.

If you come across anything that needs improvement, do let me know!

Regards,
Francisco Hodge
